### ISSUE TITLE
Modify Pocketbase API request?

### ISSUE THREAD

**Issue by bojtalepenye** [Ilyas-Codes/eCourse#18]
I have a pocketbase server running on a subdomain. Let's say: `pocketbase.domain.com`
I also run this eCourse server UI on a subdomain. Let's say `ecourse.domain.com`
When I try to login, it cannot reach the database obviously, because it sends the request to the local address.
```bash
POST http://127.0.0.1:8090/api/collections/users/auth-with-password net::ERR_CONNECTION_REFUSED
```

How would I be able to modify where eCourse sends its API request? -> pocketbase.domain.com

Important:
I have already added this to the .env file, and it didn't work
```
pi@raspberrypi:~/eCourse/ui $ cat .env
VITE_DEV_PB_URL=https://pocketbase.domain.com
VITE_PROD_PB_URL=https://pocketbase.domain.com
pi@raspberrypi:~/eCourse/ui $
```

Thanks,

**Comment by perronedotdev** [comment]
Were you able to resolve this issue? I'm having the same problem.
