### ISSUE TITLE
PocketBase 404 with Dockerfile

### ISSUE THREAD

**Issue by crstate** [Ilyas-Codes/eCourse#7]
## Description
Users experience a PocketBase 404 (Not Found) error when accessing the frontend via the designated IP address, despite the backend working properly.

## Steps to Reproduce
1. Clone the dockerfile
2. Build and run the Docker container using the dockerfile
3. Access the frontend using the designated IP address

## Expected Behavior
Users should be able to access the frontend interface without encountering a 404 error.

[Frontend View](https://i.imgur.com/49evmAN.png)
[Backend View](https://i.imgur.com/vmqFg5T.png)

**Comment by Ilyas-Codes** [comment]
my bad I forgot to add `/*` after the dist folder, this should work:

```
FROM node:20.11.1-buster

WORKDIR /

RUN git clone https://github.com/Ilyas-Codes/eCourse.git

ARG PB_VERSION=0.21.3
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /eCourse/pb

WORKDIR /eCourse/ui

RUN sed -i 's/^VITE_PROD_PB_URL=.*/VITE_PROD_PB_URL=http:\/\/127.0.0.1:8090/' .env
RUN npm install
RUN npm run build
RUN mv dist/* /eCourse/pb/pb_public

EXPOSE 8090

CMD ["/eCourse/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]
```

**Comment by crstate** [comment]
> my bad I forgot to add `/*` after the dist folder, this should work:
> ....

Still not working @Ilyas-Codes, idk what I am doing wrong but I tried also with docker-compose (to just use the dockerfile because there is no image of ecourse on the docker hub)

Here's the only log of the container
```
2024/02/28 21:26:09 Server started at http://0.0.0.0:8090
├─ REST API: http://0.0.0.0:8090/api/
└─ Admin UI: http://0.0.0.0:8090/_/
```
Essentially only pocketbase started (and it works)

Moreover... I've tried to run the app on my windows machine and it works perfectly

```
C:\Users\Administrator\Desktop\eCourse\ui>npm run dev
> ecourse@2.0.0 dev
> vite
  VITE v5.1.4  ready in 1061 ms
  ➜  Local:   http://localhost:5173/
```

Shouldn't the dockerfile do the same? I'm not an expert of Docker, but I think that this app should have two images: one of the backend (pocketbase) and another one for the ui (vite). Maybe you can achieve this better with docker-compose

**Comment by Ilyas-Codes** [comment]
weird, I just tested it and it worked fine. can you redo everything from scratch? delete the container and image and redo the build again.

**Comment by Ilyas-Codes** [comment]
@Orohym here are the steps I followed with docker:
1. create a directory somewhere and name it whatever, add the `Dockerfile` I left in my first comment in there.
2. run: `docker build -t image-name .`
3. run: `docker run -d -p 8090:8090 --name container-name image-name`
4. navigate to `localhost:8090`

**Comment by crstate** [comment]
@Ilyas-Codes I replicated your steps and it works.

I was still copying the Dockerfile example from the Readme file and that was the reason it was not working. (😅) 

Thank you

**Comment by Ilyas-Codes** [comment]
Not a problem :)
